"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.
"""
from pathlib import Path
import os
import json
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
env_file = BASE_DIR / '.env.local'
if not env_file.exists():
    env_file = BASE_DIR / '.env'
load_dotenv(env_file)
# Use the repository-level .env as a fallback for shared runtime secrets.
# Existing process variables and backend-local overrides keep precedence.
load_dotenv(BASE_DIR.parent / '.env')


def required_env(name: str) -> str:
    """Read a required secret/config value without an insecure source-code fallback."""
    value = os.environ.get(name, "").strip()
    if not value:
        raise ImproperlyConfigured(f"Required environment variable {name} is not set")
    return value


# SECURITY
SECRET_KEY = required_env("SECRET_KEY")
DEBUG = os.environ.get("DEBUG", "True").lower() in ["true", "1", "yes"]

ALLOWED_HOSTS_STR = os.environ.get("ALLOWED_HOSTS", '["*"]')
try:
    ALLOWED_HOSTS = json.loads(ALLOWED_HOSTS_STR)
except json.JSONDecodeError:
    ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_extensions",
    "channels",
    "apps.users",
    "apps.documents",
    "apps.operations",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.request_logging.RequestLoggingMiddleware",
    "core.middleware.auth_validation.AuthValidationMiddleware",
    "core.middleware.audit_logging.AuditLoggingMiddleware",
]

ROOT_URLCONF = "config.urls"
ASGI_APPLICATION = "config.asgi.application"
WSGI_APPLICATION = "config.wsgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "rag_system"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": required_env("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5433"),
        "CONN_MAX_AGE": int(os.environ.get("CONN_MAX_AGE", "0")),
        "OPTIONS": {
            "sslmode": os.environ.get("POSTGRES_SSLMODE", "prefer"),
        },
    }
}

# Auth
AUTH_USER_MODEL = 'users.Account'
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# I18N
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static & Media
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ============================================================
# REDIS & CACHING
# ============================================================
REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = os.environ.get("REDIS_PORT", "6379")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": "rag_system"
    }
}
CACHE_TTL = 60 * 10

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, int(REDIS_PORT))],
            "capacity": 200,
            "expiry": 30,
            "group_expiry": 60,
        },
    },
}

# ============================================================
# CELERY
# ============================================================
CELERY_ENABLED = os.environ.get("CELERY_ENABLED", "false").lower() in ["true", "1", "yes"]
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.environ.get("CELERY_TASK_TIME_LIMIT", "300"))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.environ.get("CELERY_TASK_SOFT_TIME_LIMIT", "240"))

# ============================================================
# AI CONFIGURATION (LLM & EMBEDDING)
# ============================================================
# 1. LLM Settings
LLM_BASE_URL = os.environ.get("LLM_BASE_URL", "http://llama-server:8080/v1")
LLM_MODEL = os.environ.get("LLM_MODEL", "Qwen3-4B-Instruct-2507-Q4_K_M.gguf")
LLM_TEMPERATURE = float(os.environ.get("LLM_TEMPERATURE", "0.7"))
LLM_TOP_P = float(os.environ.get("LLM_TOP_P", "0.9"))
LLM_MAX_TOKENS = int(os.environ.get("LLM_MAX_TOKENS", "2048"))
LLM_CONTEXT_WINDOW = int(os.environ.get("LLM_CONTEXT_WINDOW", "4096"))
LLM_REQUEST_TIMEOUT = int(os.environ.get("LLM_REQUEST_TIMEOUT", "120"))
RAG_LLM_MAX_TOKENS = int(os.environ.get("RAG_LLM_MAX_TOKENS", "768"))
RAG_LLM_TEMPERATURE = float(os.environ.get("RAG_LLM_TEMPERATURE", "0.2"))
RAG_LLM_MAX_TOKENS_LIST = int(os.environ.get("RAG_LLM_MAX_TOKENS_LIST", "1280"))
RAG_RETRIEVAL_TOP_K = int(os.environ.get("RAG_RETRIEVAL_TOP_K", "4"))
RAG_RETRIEVAL_TOP_K_LIST = int(os.environ.get("RAG_RETRIEVAL_TOP_K_LIST", "8"))
RAG_CONTEXT_SNIPPET_CHARS = int(os.environ.get("RAG_CONTEXT_SNIPPET_CHARS", "1400"))
RAG_CONTEXT_SNIPPET_CHARS_LIST = int(os.environ.get("RAG_CONTEXT_SNIPPET_CHARS_LIST", "2200"))
RAG_CONTEXT_MAX_CHARS = int(os.environ.get("RAG_CONTEXT_MAX_CHARS", "5000"))
RAG_CONTEXT_MAX_CHARS_LIST = int(os.environ.get("RAG_CONTEXT_MAX_CHARS_LIST", "7000"))
RAG_CONTEXT_MAX_CHUNKS = int(os.environ.get("RAG_CONTEXT_MAX_CHUNKS", "8"))
RAG_CONTEXT_MAX_CHUNKS_LIST = int(os.environ.get("RAG_CONTEXT_MAX_CHUNKS_LIST", "12"))
RAG_CONTEXT_NEIGHBOR_BEFORE_LIST = int(os.environ.get("RAG_CONTEXT_NEIGHBOR_BEFORE_LIST", "1"))
RAG_CONTEXT_NEIGHBOR_AFTER_LIST = int(os.environ.get("RAG_CONTEXT_NEIGHBOR_AFTER_LIST", "4"))
QUERY_REWRITE_ENABLED = os.environ.get("QUERY_REWRITE_ENABLED", "true").lower() in ["true", "1", "yes"]
QUERY_REWRITE_LLM_ENABLED = os.environ.get("QUERY_REWRITE_LLM_ENABLED", "false").lower() in ["true", "1", "yes"]
RAG_HYDE_ENABLED = os.environ.get("RAG_HYDE_ENABLED", "false").lower() in ["true", "1", "yes"]
RAG_QUERY_DECOMPOSITION_ENABLED = os.environ.get("RAG_QUERY_DECOMPOSITION_ENABLED", "false").lower() in ["true", "1", "yes"]
RAG_SELF_RAG_RELEVANCE_CHECK_ENABLED = os.environ.get("RAG_SELF_RAG_RELEVANCE_CHECK_ENABLED", "false").lower() in ["true", "1", "yes"]
RAG_GROUNDING_REVISION_ENABLED = os.environ.get("RAG_GROUNDING_REVISION_ENABLED", "true").lower() in ["true", "1", "yes"]
RAG_GROUNDING_REVISION_MAX_TOKENS = int(os.environ.get("RAG_GROUNDING_REVISION_MAX_TOKENS", "768"))
RAG_GROUNDING_VISIBLE_WARNING_ENABLED = os.environ.get("RAG_GROUNDING_VISIBLE_WARNING_ENABLED", "true").lower() in ["true", "1", "yes"]
RAG_STREAM_VERIFY_BEFORE_EMIT = os.environ.get("RAG_STREAM_VERIFY_BEFORE_EMIT", "false").lower() in ["true", "1", "yes"]
RAG_DEEP_MODE_ENABLE_LLM_STEPS = os.environ.get("RAG_DEEP_MODE_ENABLE_LLM_STEPS", "true").lower() in ["true", "1", "yes"]
RAG_PROMPT_RESERVED_TOKENS = int(os.environ.get("RAG_PROMPT_RESERVED_TOKENS", "800"))
RAG_CONTEXT_CHARS_PER_TOKEN = float(os.environ.get("RAG_CONTEXT_CHARS_PER_TOKEN", "3.2"))

# 2. Embedding Settings
EMBEDDING_BACKEND = os.environ.get("EMBEDDING_BACKEND", "http")  # 'http' or 'flag'
EMBEDDING_BASE_URL = os.environ.get("EMBEDDING_BASE_URL", LLM_BASE_URL)
EMBEDDING_MODEL = os.environ.get("EMBEDDING_MODEL", LLM_MODEL)
EMBEDDING_DEVICE = os.environ.get("EMBEDDING_DEVICE", "auto")
EMBEDDING_TIMEOUT = int(os.environ.get("EMBEDDING_TIMEOUT", "60"))
EMBEDDING_RETRY_TIMES = int(os.environ.get("EMBEDDING_RETRY_TIMES", "1"))
EMBEDDING_PRELOAD_ENABLED = os.environ.get("EMBEDDING_PRELOAD_ENABLED", "true").lower() in ["true", "1", "yes"]
EMBEDDING_PRELOAD_TEST_EMBED = os.environ.get("EMBEDDING_PRELOAD_TEST_EMBED", "true").lower() in ["true", "1", "yes"]
EMBEDDING_PRELOAD_FAIL_FAST = os.environ.get("EMBEDDING_PRELOAD_FAIL_FAST", "false").lower() in ["true", "1", "yes"]
EMBEDDING_PRELOAD_TEXT = os.environ.get("EMBEDDING_PRELOAD_TEXT", "warmup embedding model")

# Determine dimension
if EMBEDDING_BACKEND.lower() in ('flag', 'flagembedding', 'native'):
    EMBEDDING_DIMENSION = 1024  # BGE-M3
else:
    EMBEDDING_DIMENSION = 2560  # Qwen3-4B

# 3. LlamaClient Compatibility Aliases
LLAMA_API_URL = LLM_BASE_URL
LLAMA_MODEL = LLM_MODEL
LLAMA_TEMPERATURE = LLM_TEMPERATURE
LLAMA_TOP_P = LLM_TOP_P
LLAMA_MAX_TOKENS = LLM_MAX_TOKENS
LLAMA_TIMEOUT = LLM_REQUEST_TIMEOUT
LLAMA_RETRY_TIMES = int(os.environ.get("LLAMA_RETRY_TIMES", "3"))

# ============================================================
# QDRANT (Vector Database)
# ============================================================
QDRANT_HOST = os.environ.get("QDRANT_HOST", "localhost")
QDRANT_PORT = os.environ.get("QDRANT_PORT", "6333")
QDRANT_API_KEY = required_env("QDRANT_API_KEY")
QDRANT_URL = f"http://{QDRANT_HOST}:{QDRANT_PORT}"
QDRANT_COLLECTION = os.environ.get("QDRANT_COLLECTION", "documents")
QDRANT_VECTOR_SIZE = EMBEDDING_DIMENSION
QDRANT_TIMEOUT = int(os.environ.get("QDRANT_TIMEOUT", "30"))
QDRANT_RETRY_TIMES = int(os.environ.get("QDRANT_RETRY_TIMES", "3"))

# Search Optimization
QDRANT_HNSW_M = int(os.environ.get("QDRANT_HNSW_M", "16"))
QDRANT_HNSW_EF_CONSTRUCTION = int(os.environ.get("QDRANT_HNSW_EF_CONSTRUCTION", "256"))
QDRANT_SEARCH_EF = int(os.environ.get("QDRANT_SEARCH_EF", "128"))
QDRANT_FULL_SCAN_THRESHOLD = int(os.environ.get("QDRANT_FULL_SCAN_THRESHOLD", "100"))
QDRANT_QUANTIZATION = os.environ.get("QDRANT_QUANTIZATION", "")

# ============================================================
# CHUNKING
# ============================================================
CHUNK_TOKEN_SIZE = int(os.environ.get("CHUNK_TOKEN_SIZE", "360"))
CHUNK_TOKEN_OVERLAP = int(os.environ.get("CHUNK_TOKEN_OVERLAP", "72"))
CHUNK_TOKEN_SIZE_PDF = int(os.environ.get("CHUNK_TOKEN_SIZE_PDF", "320"))
CHUNK_TOKEN_OVERLAP_PDF = int(os.environ.get("CHUNK_TOKEN_OVERLAP_PDF", "64"))
CHUNK_TOKEN_SIZE_DOC = int(os.environ.get("CHUNK_TOKEN_SIZE_DOC", "420"))
CHUNK_TOKEN_OVERLAP_DOC = int(os.environ.get("CHUNK_TOKEN_OVERLAP_DOC", "84"))
CHUNK_TOKEN_SIZE_TEXT = int(os.environ.get("CHUNK_TOKEN_SIZE_TEXT", "360"))
CHUNK_TOKEN_OVERLAP_TEXT = int(os.environ.get("CHUNK_TOKEN_OVERLAP_TEXT", "72"))
CHUNK_TOKEN_SIZE_SPREADSHEET = int(os.environ.get("CHUNK_TOKEN_SIZE_SPREADSHEET", "520"))
CHUNK_TOKEN_OVERLAP_SPREADSHEET = int(os.environ.get("CHUNK_TOKEN_OVERLAP_SPREADSHEET", "80"))

# -- Vietnamese document-type chunk profiles ---------------------------------
# These override base profiles when document type is auto-detected.
# Regulations (nghị định, thông tư): larger chunks with high overlap for legal context
CHUNK_TOKEN_SIZE_REGULATION = int(os.environ.get("CHUNK_TOKEN_SIZE_REGULATION", "480"))
CHUNK_TOKEN_OVERLAP_REGULATION = int(os.environ.get("CHUNK_TOKEN_OVERLAP_REGULATION", "96"))
# Contracts (hợp đồng): medium chunks, high overlap for clause linking
CHUNK_TOKEN_SIZE_CONTRACT = int(os.environ.get("CHUNK_TOKEN_SIZE_CONTRACT", "400"))
CHUNK_TOKEN_OVERLAP_CONTRACT = int(os.environ.get("CHUNK_TOKEN_OVERLAP_CONTRACT", "100"))
# Handbooks (sổ tay, hướng dẫn): standard chunks
CHUNK_TOKEN_SIZE_HANDBOOK = int(os.environ.get("CHUNK_TOKEN_SIZE_HANDBOOK", "360"))
CHUNK_TOKEN_OVERLAP_HANDBOOK = int(os.environ.get("CHUNK_TOKEN_OVERLAP_HANDBOOK", "72"))
# Reports (báo cáo): larger chunks for comprehensive context
CHUNK_TOKEN_SIZE_REPORT = int(os.environ.get("CHUNK_TOKEN_SIZE_REPORT", "500"))
CHUNK_TOKEN_OVERLAP_REPORT = int(os.environ.get("CHUNK_TOKEN_OVERLAP_REPORT", "80"))
# Technical docs: smaller chunks for precise retrieval
CHUNK_TOKEN_SIZE_TECHNICAL = int(os.environ.get("CHUNK_TOKEN_SIZE_TECHNICAL", "280"))
CHUNK_TOKEN_OVERLAP_TECHNICAL = int(os.environ.get("CHUNK_TOKEN_OVERLAP_TECHNICAL", "56"))

CHUNK_SIZE = CHUNK_TOKEN_SIZE
CHUNK_OVERLAP = CHUNK_TOKEN_OVERLAP

# -- Chunk Quality Validation ------------------------------------------------
CHUNK_VALIDATOR_ENABLED = os.environ.get("CHUNK_VALIDATOR_ENABLED", "true").lower() in ["true", "1", "yes"]
CHUNK_VALIDATOR_MIN_CHARS = int(os.environ.get("CHUNK_VALIDATOR_MIN_CHARS", "50"))
CHUNK_VALIDATOR_MAX_CHARS = int(os.environ.get("CHUNK_VALIDATOR_MAX_CHARS", "6000"))
CHUNK_VALIDATOR_MIN_TOKENS = int(os.environ.get("CHUNK_VALIDATOR_MIN_TOKENS", "20"))
CHUNK_VALIDATOR_MAX_TOKENS = int(os.environ.get("CHUNK_VALIDATOR_MAX_TOKENS", "5000"))
CHUNK_VALIDATOR_MIN_OVERLAP = float(os.environ.get("CHUNK_VALIDATOR_MIN_OVERLAP", "0.0"))
CHUNK_VALIDATOR_MAX_OVERLAP = float(os.environ.get("CHUNK_VALIDATOR_MAX_OVERLAP", "0.80"))
CHUNK_VALIDATOR_DUPE_SIMILARITY = float(os.environ.get("CHUNK_VALIDATOR_DUPE_SIMILARITY", "0.92"))

POSTGRES_FTS_CONFIG = os.environ.get("POSTGRES_FTS_CONFIG", "simple")

# ============================================================
# REST FRAMEWORK & JWT
# ============================================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated",],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer",],
    "EXCEPTION_HANDLER": "api.exceptions.global_exception_handler",
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%SZ",
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# CORS
CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]
cors_origins_str = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if cors_origins_str:
    try:
        CORS_ALLOWED_ORIGINS = json.loads(cors_origins_str)
    except json.JSONDecodeError:
        pass
CORS_ALLOW_CREDENTIALS = True
# Cần thiết để SSE streaming từ browser gọi trực tiếp backend hoạt động
CORS_ALLOW_ALL_HEADERS = True
CORS_EXPOSE_HEADERS = ["Content-Type", "X-Accel-Buffering"]
APPEND_SLASH = False

# ============================================================
# LOGGING
# ============================================================
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "[{levelname}] {asctime} {name}:{lineno} - {message}", "style": "{"},
    },
    "handlers": {
        "console": {"level": "DEBUG" if DEBUG else "INFO", "class": "logging.StreamHandler"},
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "django.log",
            "maxBytes": 1024 * 1024 * 10,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {"handlers": ["console", "file"], "level": "INFO", "propagate": True},
        "api": {"handlers": ["console", "file"], "level": "DEBUG" if DEBUG else "INFO", "propagate": False},
        "services": {"handlers": ["console", "file"], "level": "DEBUG" if DEBUG else "INFO", "propagate": False},
    },
}

# Others
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600
TEMP_UPLOAD_DIR = BASE_DIR / "uploads" / "temp"
TEMP_UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

# Email
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("SMTP_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("SMTP_USE_TLS", "True").lower() in ["true", "1"]
EMAIL_HOST_USER = os.environ.get("SMTP_USERNAME", "")
EMAIL_HOST_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("EMAIL_SENDER", EMAIL_HOST_USER or "noreply@localhost")

FRONTEND_URL = os.environ.get("APP_URL", "http://localhost:3000")
# RAG Pipeline Settings
RAG_RAPTOR_THRESHOLD_PAGES = int(os.environ.get("RAG_RAPTOR_THRESHOLD_PAGES", "3"))
RAG_RAPTOR_CLUSTERING_ENABLED = os.environ.get("RAG_RAPTOR_CLUSTERING_ENABLED", "true").lower() in ["true", "1", "yes"]
RAG_RAPTOR_MAX_DEPTH = int(os.environ.get("RAG_RAPTOR_MAX_DEPTH", "4"))
RAG_RAPTOR_PAGE_WINDOW_SIZE = int(os.environ.get("RAG_RAPTOR_PAGE_WINDOW_SIZE", "3"))
RAG_RAPTOR_MIN_CLUSTER_SIZE = int(os.environ.get("RAG_RAPTOR_MIN_CLUSTER_SIZE", "4"))
RAG_RAPTOR_MAX_CLUSTERS = int(os.environ.get("RAG_RAPTOR_MAX_CLUSTERS", "8"))
RAG_RAPTOR_UMAP_NEIGHBORS = int(os.environ.get("RAG_RAPTOR_UMAP_NEIGHBORS", "15"))
RAG_RAPTOR_UMAP_COMPONENTS = int(os.environ.get("RAG_RAPTOR_UMAP_COMPONENTS", "5"))
RAG_RAPTOR_GMM_MEMBERSHIP_THRESHOLD = float(os.environ.get("RAG_RAPTOR_GMM_MEMBERSHIP_THRESHOLD", "0.10"))
RAG_RAPTOR_MAX_MEMBERSHIPS_PER_NODE = int(os.environ.get("RAG_RAPTOR_MAX_MEMBERSHIPS_PER_NODE", "3"))
RAG_RAPTOR_RANDOM_STATE = int(os.environ.get("RAG_RAPTOR_RANDOM_STATE", "42"))
RAG_RAPTOR_LLM_SUMMARIES = os.environ.get("RAG_RAPTOR_LLM_SUMMARIES", "false").lower() in ["true", "1", "yes"]
RAG_UPLOAD_FAST_MODE = os.environ.get("RAG_UPLOAD_FAST_MODE", "false").lower() in ["true", "1", "yes"]
RAG_DEFER_SUMMARY_ON_UPLOAD = os.environ.get("RAG_DEFER_SUMMARY_ON_UPLOAD", "false").lower() in ["true", "1", "yes"]
RAG_BUILD_RAPTOR_ON_UPLOAD = os.environ.get("RAG_BUILD_RAPTOR_ON_UPLOAD", "true").lower() in ["true", "1", "yes"]
RAG_QUEUE_SECTION_SUMMARIES_ON_UPLOAD = os.environ.get("RAG_QUEUE_SECTION_SUMMARIES_ON_UPLOAD", "false").lower() in ["true", "1", "yes"]
RAG_SUMMARIZE_DETAIL_CHUNKS_ON_UPLOAD = os.environ.get("RAG_SUMMARIZE_DETAIL_CHUNKS_ON_UPLOAD", "false").lower() in ["true", "1", "yes"]
RAG_CREATE_PAGE_CONTAINERS_ON_UPLOAD = os.environ.get("RAG_CREATE_PAGE_CONTAINERS_ON_UPLOAD", "false").lower() in ["true", "1", "yes"]
RAG_RAPTOR_BUILD_WORKERS = int(os.environ.get("RAG_RAPTOR_BUILD_WORKERS", "1"))
RAG_RAPTOR_DESCENDANT_LIMIT = int(os.environ.get("RAG_RAPTOR_DESCENDANT_LIMIT", "80"))
RAG_TABLE_CHUNK_MAX_TOKENS = int(os.environ.get("RAG_TABLE_CHUNK_MAX_TOKENS", "1600"))
RAG_MAX_ASSET_RESULTS = int(os.environ.get("RAG_MAX_ASSET_RESULTS", "4"))
RAG_VECTORIZE_PAGE_SECTIONS = os.environ.get("RAG_VECTORIZE_PAGE_SECTIONS", "false").lower() in ["true", "1", "yes"]
RAG_CONTEXTUAL_EMBEDDING_PREFIX_ENABLED = os.environ.get("RAG_CONTEXTUAL_EMBEDDING_PREFIX_ENABLED", "true").lower() in ["true", "1", "yes"]
RAG_CONTEXTUAL_EMBEDDING_PREFIX_CHARS = int(os.environ.get("RAG_CONTEXTUAL_EMBEDDING_PREFIX_CHARS", "360"))
RAG_RAPTOR_TASK_TIME_LIMIT = int(os.environ.get("RAG_RAPTOR_TASK_TIME_LIMIT", "1800"))
RAG_RAPTOR_TASK_SOFT_TIME_LIMIT = int(os.environ.get("RAG_RAPTOR_TASK_SOFT_TIME_LIMIT", "1500"))
RAG_SPREADSHEET_RAPTOR_ENABLED = os.environ.get("RAG_SPREADSHEET_RAPTOR_ENABLED", "true").lower() in ["true", "1", "yes"]
RAG_SPREADSHEET_RAPTOR_MIN_SHEETS = int(os.environ.get("RAG_SPREADSHEET_RAPTOR_MIN_SHEETS", "3"))
RAG_SPREADSHEET_RAPTOR_MIN_ROWS = int(os.environ.get("RAG_SPREADSHEET_RAPTOR_MIN_ROWS", "200"))
RAG_SPREADSHEET_RAPTOR_MIN_CHUNKS = int(os.environ.get("RAG_SPREADSHEET_RAPTOR_MIN_CHUNKS", "12"))
RAG_PDF_EXACT_PAGE_TEXT = os.environ.get("RAG_PDF_EXACT_PAGE_TEXT", "true").lower() in ["true", "1", "yes"]
RAG_PDF_OCR_FALLBACK_ENABLED = os.environ.get("RAG_PDF_OCR_FALLBACK_ENABLED", "true").lower() in ["true", "1", "yes"]
RAG_PDF_OCR_PAGE_TEXT_MIN_CHARS = int(os.environ.get("RAG_PDF_OCR_PAGE_TEXT_MIN_CHARS", "40"))
RAG_PDF_OCR_EMPTY_PAGE_RATIO = float(os.environ.get("RAG_PDF_OCR_EMPTY_PAGE_RATIO", "0.60"))
RAG_PDF_OCR_DPI = int(os.environ.get("RAG_PDF_OCR_DPI", "180"))
RAG_PDF_OCR_MAX_PAGES = int(os.environ.get("RAG_PDF_OCR_MAX_PAGES", "300"))
RAG_QDRANT_TEXT_PREVIEW_CHARS = int(os.environ.get("RAG_QDRANT_TEXT_PREVIEW_CHARS", "1000"))
RAG_RERANK_SNIPPET_CHARS = int(os.environ.get("RAG_RERANK_SNIPPET_CHARS", "1800"))

# ============================================================
# ASSET PIPELINE (OCR + VL Caption + Image Extraction)
# ============================================================
ASSET_PIPELINE_ENABLED = os.environ.get("ASSET_PIPELINE_ENABLED", "true").lower() in ["true", "1", "yes"]
ASSET_PROCESS_INLINE_ON_UPLOAD = os.environ.get("ASSET_PROCESS_INLINE_ON_UPLOAD", "false").lower() in ["true", "1", "yes"]
ASSET_PROCESS_ASYNC_ON_UPLOAD = os.environ.get("ASSET_PROCESS_ASYNC_ON_UPLOAD", "true").lower() in ["true", "1", "yes"]
ASSET_OCR_ENABLED = os.environ.get("ASSET_OCR_ENABLED", "true").lower() in ["true", "1", "yes"]
ASSET_OCR_ENGINE = os.environ.get("ASSET_OCR_ENGINE", "tesseract")
ASSET_OCR_LANGUAGES = os.environ.get("ASSET_OCR_LANGUAGES", "vie+eng")
ASSET_PADDLEOCR_LANG = os.environ.get("ASSET_PADDLEOCR_LANG", "vi")
ASSET_VL_CAPTION_ENABLED = os.environ.get("ASSET_VL_CAPTION_ENABLED", "false").lower() in ["true", "1", "yes"]
ASSET_EMBED_CAPTIONS = os.environ.get("ASSET_EMBED_CAPTIONS", "true").lower() in ["true", "1", "yes"]
ASSET_CAPTION_METHOD = os.environ.get("ASSET_CAPTION_METHOD", "vl-model")  # 'vl-model' or 'rule-based'
ASSET_MAX_IMAGES_PER_DOC = int(os.environ.get("ASSET_MAX_IMAGES_PER_DOC", "50"))
ASSET_MIN_IMAGE_SIZE_BYTES = int(os.environ.get("ASSET_MIN_IMAGE_SIZE_BYTES", "1024"))
ASSET_IMAGE_MAX_WIDTH = int(os.environ.get("ASSET_IMAGE_MAX_WIDTH", "2000"))
ASSET_TASK_TIME_LIMIT = int(os.environ.get("ASSET_TASK_TIME_LIMIT", "1800"))
ASSET_TASK_SOFT_TIME_LIMIT = int(os.environ.get("ASSET_TASK_SOFT_TIME_LIMIT", "1500"))
QDRANT_ASSET_VECTOR_SIZE = int(os.environ.get("QDRANT_ASSET_VECTOR_SIZE", str(QDRANT_VECTOR_SIZE)))

# VL Model (Qwen2.5-VL-3B) for image captioning
VL_MODEL_BASE_URL = os.environ.get("VL_MODEL_BASE_URL", "http://llama-vl-server:8081/v1")
VL_MODEL_NAME = os.environ.get("VL_MODEL_NAME", "Qwen2.5-VL-3B-Instruct")
VL_MODEL_TIMEOUT = int(os.environ.get("VL_MODEL_TIMEOUT", "300"))
VL_MODEL_MAX_TOKENS = int(os.environ.get("VL_MODEL_MAX_TOKENS", "256"))
VL_MODEL_TEMPERATURE = float(os.environ.get("VL_MODEL_TEMPERATURE", "0.3"))

# Query rewrite settings are defined with the main RAG settings above.
