"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.
"""
from pathlib import Path
import os
import json
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
env_file = BASE_DIR / '.env.local'
if not env_file.exists():
    env_file = BASE_DIR / '.env'
load_dotenv(env_file)

# SECURITY
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-hy)noycf61-^32x=vy4@b7*vxo1+a++1d7%d%ff1^(ya&ekle)")
DEBUG = os.environ.get("DEBUG", "True").lower() in ["true", "1", "yes"]

ALLOWED_HOSTS_STR = os.environ.get("ALLOWED_HOSTS", '["*"]')
try:
    ALLOWED_HOSTS = json.loads(ALLOWED_HOSTS_STR)
except json.JSONDecodeError:
    ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_extensions",
    "channels",
    "apps.users",
    "apps.documents",
    "apps.operations",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.request_logging.RequestLoggingMiddleware",
    "core.middleware.auth_validation.AuthValidationMiddleware",
    "core.middleware.audit_logging.AuditLoggingMiddleware",
]

ROOT_URLCONF = "config.urls"
ASGI_APPLICATION = "config.asgi.application"
WSGI_APPLICATION = "config.wsgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "rag_system"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5433"),
        "CONN_MAX_AGE": int(os.environ.get("CONN_MAX_AGE", "60")),
        "OPTIONS": {
            "sslmode": os.environ.get("POSTGRES_SSLMODE", "prefer"),
        },
    }
}

# Auth
AUTH_USER_MODEL = 'users.Account'
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# I18N
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static & Media
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ============================================================
# REDIS & CACHING
# ============================================================
REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = os.environ.get("REDIS_PORT", "6379")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": "rag_system"
    }
}
CACHE_TTL = 60 * 10

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, int(REDIS_PORT))],
        },
    },
}

# ============================================================
# CELERY
# ============================================================
CELERY_ENABLED = os.environ.get("CELERY_ENABLED", "false").lower() in ["true", "1", "yes"]
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300

# ============================================================
# AI CONFIGURATION (LLM & EMBEDDING)
# ============================================================
# 1. LLM Settings
LLM_BASE_URL = os.environ.get("LLM_BASE_URL", "http://llama-server:8080/v1")
LLM_MODEL = os.environ.get("LLM_MODEL", "Qwen3-4B-Instruct-2507-Q4_K_M.gguf")
LLM_TEMPERATURE = float(os.environ.get("LLM_TEMPERATURE", "0.7"))
LLM_TOP_P = float(os.environ.get("LLM_TOP_P", "0.9"))
LLM_MAX_TOKENS = int(os.environ.get("LLM_MAX_TOKENS", "2048"))
LLM_CONTEXT_WINDOW = int(os.environ.get("LLM_CONTEXT_WINDOW", "8192"))
LLM_REQUEST_TIMEOUT = int(os.environ.get("LLM_REQUEST_TIMEOUT", "120"))

# 2. Embedding Settings
EMBEDDING_BACKEND = os.environ.get("EMBEDDING_BACKEND", "http")  # 'http' or 'flag'
EMBEDDING_BASE_URL = os.environ.get("EMBEDDING_BASE_URL", LLM_BASE_URL)
EMBEDDING_MODEL = os.environ.get("EMBEDDING_MODEL", LLM_MODEL)
EMBEDDING_DEVICE = os.environ.get("EMBEDDING_DEVICE", "cpu")
EMBEDDING_TIMEOUT = int(os.environ.get("EMBEDDING_TIMEOUT", "60"))
EMBEDDING_RETRY_TIMES = int(os.environ.get("EMBEDDING_RETRY_TIMES", "1"))

# Determine dimension
if EMBEDDING_BACKEND.lower() in ('flag', 'flagembedding', 'native'):
    EMBEDDING_DIMENSION = 1024  # BGE-M3
else:
    EMBEDDING_DIMENSION = 2560  # Qwen3-4B

# 3. LlamaClient Compatibility Aliases
LLAMA_API_URL = LLM_BASE_URL
LLAMA_MODEL = LLM_MODEL
LLAMA_TEMPERATURE = LLM_TEMPERATURE
LLAMA_TOP_P = LLM_TOP_P
LLAMA_MAX_TOKENS = LLM_MAX_TOKENS
LLAMA_TIMEOUT = LLM_REQUEST_TIMEOUT
LLAMA_RETRY_TIMES = int(os.environ.get("LLAMA_RETRY_TIMES", "3"))

# ============================================================
# QDRANT (Vector Database)
# ============================================================
QDRANT_HOST = os.environ.get("QDRANT_HOST", "localhost")
QDRANT_PORT = os.environ.get("QDRANT_PORT", "6333")
QDRANT_API_KEY = os.environ.get("QDRANT_API_KEY", "qdrant")
QDRANT_URL = f"http://{QDRANT_HOST}:{QDRANT_PORT}"
QDRANT_COLLECTION = os.environ.get("QDRANT_COLLECTION", "documents")
QDRANT_VECTOR_SIZE = EMBEDDING_DIMENSION
QDRANT_TIMEOUT = int(os.environ.get("QDRANT_TIMEOUT", "30"))
QDRANT_RETRY_TIMES = int(os.environ.get("QDRANT_RETRY_TIMES", "3"))

# Search Optimization
QDRANT_HNSW_M = int(os.environ.get("QDRANT_HNSW_M", "16"))
QDRANT_HNSW_EF_CONSTRUCTION = int(os.environ.get("QDRANT_HNSW_EF_CONSTRUCTION", "256"))
QDRANT_SEARCH_EF = int(os.environ.get("QDRANT_SEARCH_EF", "128"))
QDRANT_FULL_SCAN_THRESHOLD = int(os.environ.get("QDRANT_FULL_SCAN_THRESHOLD", "100"))
QDRANT_QUANTIZATION = os.environ.get("QDRANT_QUANTIZATION", "")

# ============================================================
# CHUNKING
# ============================================================
CHUNK_TOKEN_SIZE = int(os.environ.get("CHUNK_TOKEN_SIZE", "240"))
CHUNK_TOKEN_OVERLAP = int(os.environ.get("CHUNK_TOKEN_OVERLAP", "48"))
CHUNK_SIZE = CHUNK_TOKEN_SIZE
CHUNK_OVERLAP = CHUNK_TOKEN_OVERLAP

# ============================================================
# REST FRAMEWORK & JWT
# ============================================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated",],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer",],
    "EXCEPTION_HANDLER": "api.exceptions.global_exception_handler",
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%SZ",
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# CORS
CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]
cors_origins_str = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if cors_origins_str:
    try:
        CORS_ALLOWED_ORIGINS = json.loads(cors_origins_str)
    except json.JSONDecodeError:
        pass
CORS_ALLOW_CREDENTIALS = True
# Cần thiết để SSE streaming từ browser gọi trực tiếp backend hoạt động
CORS_ALLOW_ALL_HEADERS = True
CORS_EXPOSE_HEADERS = ["Content-Type", "X-Accel-Buffering"]
APPEND_SLASH = False

# ============================================================
# LOGGING
# ============================================================
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "[{levelname}] {asctime} {name}:{lineno} - {message}", "style": "{"},
    },
    "handlers": {
        "console": {"level": "DEBUG" if DEBUG else "INFO", "class": "logging.StreamHandler"},
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "django.log",
            "maxBytes": 1024 * 1024 * 10,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {"handlers": ["console", "file"], "level": "INFO", "propagate": True},
        "api": {"handlers": ["console", "file"], "level": "DEBUG" if DEBUG else "INFO", "propagate": False},
        "services": {"handlers": ["console", "file"], "level": "DEBUG" if DEBUG else "INFO", "propagate": False},
    },
}

# Others
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600
TEMP_UPLOAD_DIR = BASE_DIR / "uploads" / "temp"
TEMP_UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

# Email
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("SMTP_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("SMTP_USE_TLS", "True").lower() in ["true", "1"]
EMAIL_HOST_USER = os.environ.get("SMTP_USERNAME", "phuongbinh732004@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("SMTP_PASSWORD", "wtgr smng iswt twjm")
DEFAULT_FROM_EMAIL = os.environ.get("EMAIL_SENDER", EMAIL_HOST_USER)

FRONTEND_URL = os.environ.get("APP_URL", "http://localhost:3000")
# RAG Pipeline Settings
RAG_RAPTOR_THRESHOLD_PAGES = 3  # Only apply RAPTOR/Hierarchical logic for docs > 3 pages

# Query Rewriter (P2#10)
QUERY_REWRITE_ENABLED = os.environ.get("QUERY_REWRITE_ENABLED", "true").lower() in ["true", "1", "yes"]
