"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env.local (git-ignored)
# Falls back to .env if .env.local doesn't exist
env_file = BASE_DIR / '.env.local'
if not env_file.exists():
    env_file = BASE_DIR / '.env'
load_dotenv(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-hy)noycf61-^32x=vy4@b7*vxo1+a++1d7%d%ff1^(ya&ekle)"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ["true", "1", "yes"]

# Parse ALLOWED_HOSTS from env - Use wildcard for development
import json
ALLOWED_HOSTS_STR = os.environ.get("ALLOWED_HOSTS", '["*"]')
try:
    ALLOWED_HOSTS = json.loads(ALLOWED_HOSTS_STR)
except json.JSONDecodeError:
    ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",              # CORS support
    "django_extensions",        # TimeStampedModel for BaseModel
    "apps.users",
    "apps.documents",
    "apps.operations",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS - thêm sớm
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom middleware
    "core.middleware.request_logging.RequestLoggingMiddleware",  # Request-ID, logging
    "core.middleware.auth_validation.AuthValidationMiddleware",  # ✅ NEW: Validate user status (blocked/deleted)
    "core.middleware.audit_logging.AuditLoggingMiddleware",  # Audit trail
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "rag_system"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5433"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ============================================================
# LLM & EMBEDDING CONFIGURATION
# ============================================================
LLM_BASE_URL = os.environ.get("LLM_BASE_URL", "http://localhost:11434/v1")
LLM_MODEL = os.environ.get("LLM_MODEL", "Qwen3-4B-Instruct-2507-Q4_K_M.gguf")
EMBEDDING_BASE_URL = os.environ.get("EMBEDDING_BASE_URL", LLM_BASE_URL)
EMBEDDING_MODEL = os.environ.get("EMBEDDING_MODEL", LLM_MODEL)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Disable trailing slash redirect for REST API
# REST APIs handle URLs explicitly, no need for Django's APPEND_SLASH redirect
APPEND_SLASH = False

# Sử dụng mô hình User riêng cho ứng dụng
AUTH_USER_MODEL = 'users.Account'

# ============================================================
# CACHING (REDIS)
# ============================================================
REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = os.environ.get("REDIS_PORT", "6379")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True, # Nếu Redis lỗi, Backend vẫn chạy bằng DB
        },
        "KEY_PREFIX": "rag_system"
    }
}

# Thời gian sống mặc định của Cache (10 phút)
CACHE_TTL = 60 * 10


# ============================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================
REST_FRAMEWORK = {
    # Authentication
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    
    # Permissions
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    
    # Pagination
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    
    # Filtering
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    
    # Schema (Swagger/OpenAPI)
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    
    # Renderers (JSON default)
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    
    # Exception Handler (CUSTOM - sẽ tạo file riêng)
    "EXCEPTION_HANDLER": "api.exceptions.global_exception_handler",
    
    # Datetime Format
    "DATETIME_FORMAT": "%Y-%m-%dT%H:%M:%SZ",
    
    # Throttling
    "DEFAULT_THROTTLE_CLASSES": [] if DEBUG else [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour"
    },
}


# ============================================================
# JWT (Simple JWT) CONFIGURATION
# ============================================================
from datetime import timedelta
from django.conf import settings as django_settings

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # 15 min
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),  # 7 days
    "ROTATE_REFRESH_TOKENS": True,  # Tạo refresh token mới sau mỗi lần refresh
    "BLACKLIST_AFTER_ROTATION": True,  # Vô hiệu hóa token cũ
    
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    
    "JTI_CLAIM": "jti",
    
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=1),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=7),
}


# ============================================================
# CORS (Cross-Origin Resource Sharing)
# ============================================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Parse CORS origins từ env nếu có
cors_origins_str = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if cors_origins_str:
    try:
        CORS_ALLOWED_ORIGINS = json.loads(cors_origins_str)
    except json.JSONDecodeError:
        pass

CORS_ALLOW_CREDENTIALS = True
CORS_MAX_AGE = 600

# Allow custom headers from frontend
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-request-id',          # Custom: Request tracking ID
    'x-api-version',         # Custom: API version
    'x-timestamp',           # Custom: Request timestamp
]

# Expose headers to frontend
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-request-id',          # Return request ID
    'x-ratelimit-limit',     # Rate limit info
    'x-ratelimit-remaining',
    'x-ratelimit-reset',
]


# ============================================================
# MIDDLEWARE ADDITIONS (Thêm vào MIDDLEWARE list)
# ============================================================
# Thêm CORS middleware vào đầu (sau SecurityMiddleware)
# Thêm custom logging & audit middleware
# Sẽ update MIDDLEWARE list ở trên


# ============================================================
# QDRANT (Vector Database) CONFIGURATION
# ============================================================
QDRANT_HOST = os.environ.get("QDRANT_HOST", "localhost")
QDRANT_PORT = os.environ.get("QDRANT_PORT", "6333")
QDRANT_API_KEY = os.environ.get("QDRANT_API_KEY", "qdrant")
QDRANT_COLLECTION_NAME = os.environ.get("QDRANT_COLLECTION_NAME", "documents")
QDRANT_URL = f"http://{QDRANT_HOST}:{QDRANT_PORT}"


# ============================================================
# LLM API CONFIGURATION (Enhanced)
# ============================================================
# Sử dụng llama.cpp server endpoint (chuẩn OpenAI compatible)
LLM_API_URL = os.environ.get(
    "LLM_BASE_URL",
    "http://llama-server:8080/v1"  # Docker compose service name
)
LLM_MODEL_NAME = os.environ.get("LLM_MODEL", "Qwen3-4B-Instruct-2507-Q4_K_M.gguf")

# Aliases for LlamaClient compatibility
LLAMA_API_URL = LLM_API_URL
LLAMA_MODEL = LLM_MODEL_NAME

# Embedding configuration
EMBEDDING_API_URL = os.environ.get("EMBEDDING_BASE_URL", LLM_API_URL)
EMBEDDING_MODEL_NAME = os.environ.get("EMBEDDING_MODEL", LLM_MODEL_NAME)
EMBEDDING_DIMENSION = 2560  # Qwen3-4B embedding dimension

# LLM Parameters
LLM_TEMPERATURE = float(os.environ.get("LLM_TEMPERATURE", "0.7"))
LLM_TOP_P = float(os.environ.get("LLM_TOP_P", "0.9"))
LLM_MAX_TOKENS = int(os.environ.get("LLM_MAX_TOKENS", "2048"))
LLM_CONTEXT_WINDOW = int(os.environ.get("LLM_CONTEXT_WINDOW", "8192"))

# Backward-compatible aliases used by services.ai.llama_client
LLAMA_TEMPERATURE = LLM_TEMPERATURE
LLAMA_TOP_P = LLM_TOP_P
LLAMA_MAX_TOKENS = LLM_MAX_TOKENS
LLAMA_TIMEOUT = int(os.environ.get("LLAMA_TIMEOUT", str(os.environ.get("LLM_REQUEST_TIMEOUT", "120"))))
LLAMA_RETRY_TIMES = int(os.environ.get("LLAMA_RETRY_TIMES", "3"))

# Request timeouts
LLM_REQUEST_TIMEOUT = 120  # 2 minutes for LLM requests
EMBEDDING_REQUEST_TIMEOUT = 60  # 1 minute for embedding request

# Aliases for Qdrant compatibility
QDRANT_COLLECTION = QDRANT_COLLECTION_NAME
QDRANT_VECTOR_SIZE = EMBEDDING_DIMENSION


# ============================================================
# CHUNKING CONFIGURATION
# ============================================================
# Recommended balanced defaults for RAG retrieval quality/speed.
CHUNK_TOKEN_SIZE = int(os.environ.get("CHUNK_TOKEN_SIZE", "240"))
CHUNK_TOKEN_OVERLAP = int(os.environ.get("CHUNK_TOKEN_OVERLAP", "48"))

# Legacy aliases used by older code paths.
CHUNK_SIZE = CHUNK_TOKEN_SIZE
CHUNK_OVERLAP = CHUNK_TOKEN_OVERLAP


# ============================================================
# LOGGING CONFIGURATION
# ============================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}:{lineno} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "maxBytes": 1024 * 1024 * 10,  # 10MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "audit_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "audit.log",
            "maxBytes": 1024 * 1024 * 50,  # 50MB
            "backupCount": 10,
            "formatter": "verbose",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "error.log",
            "maxBytes": 1024 * 1024 * 10,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file", "error_file"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "file", "error_file"],
            "level": "ERROR",
            "propagate": False,
        },
        "api": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "audit": {
            "handlers": ["audit_file"],
            "level": "INFO",
            "propagate": False,
        },
        "services": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "repositories": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}


# ============================================================
# SECURITY SETTINGS (Production Ready)
# ============================================================
if not DEBUG:
    # HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content Security
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
    }


# ============================================================
# FILE UPLOAD SETTINGS
# ============================================================
# Create logs directory if not exists
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Temp upload path
TEMP_UPLOAD_DIR = BASE_DIR / "uploads" / "temp"
TEMP_UPLOAD_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# EMAIL CONFIGURATION
# ============================================================
# SMTP Server Configuration (Gmail)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("SMTP_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("SMTP_USE_TLS", "True").lower() in ["true", "1"]
EMAIL_HOST_USER = os.environ.get("SMTP_USERNAME", "phuongbinh732004@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("SMTP_PASSWORD", "wtgr smng iswt twjm")
DEFAULT_FROM_EMAIL = os.environ.get("EMAIL_SENDER", EMAIL_HOST_USER)


# ============================================================
# FRONTEND CONFIGURATION
# ============================================================
# Frontend URL for links in emails
FRONTEND_URL = os.environ.get("APP_URL", "http://localhost:3000")

