import type { SVGProps } from 'react'
import {
    AlertCircle,
    ArrowLeft,
    ArrowRight,
    Badge,
    BadgeCheck,
    BadgeInfo,
    Box,
    BriefcaseBusiness,
    Building,
    Building2,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsDown,
    ChevronsUp,
    CircleOff,
    Code2,
    Database,
    Download,
    Edit3,
    Eye,
    FileArchive,
    FileSpreadsheet,
    FileText,
    FileUp,
    Folder,
    FolderOpen,
    FolderPlus,
    GitFork,
    Image,
    Inbox,
    Info,
    Landmark,
    List,
    Lock,
    Mail,
    Megaphone,
    MinusCircle,
    Network,
    Phone,
    Plus,
    PlusCircle,
    Presentation,
    Radio,
    RefreshCw,
    Search,
    Share2,
    Shield,
    ShieldCheck,
    Trash2,
    TrendingUp,
    Upload,
    UploadCloud,
    User,
    UserCheck,
    UserX,
    UsersRound,
    Video,
    Waypoints,
    Wrench,
    X,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { cn } from '@/lib/utils'

type AppIconProps = Omit<SVGProps<SVGSVGElement>, 'name'> & {
    name?: string | null
}

const iconMap: Record<string, LucideIcon> = {
    account_tree: Network,
    add: Plus,
    add_business: Building2,
    add_circle: PlusCircle,
    apartment: Building2,
    arrow_back: ArrowLeft,
    arrow_forward: ArrowRight,
    article: FileText,
    badge: Badge,
    business: BriefcaseBusiness,
    calendar_month: Calendar,
    call: Phone,
    campaign: Megaphone,
    check: Check,
    check_circle: CheckCircle,
    chevron_left: ChevronLeft,
    chevron_right: ChevronRight,
    close: X,
    cloud_upload: UploadCloud,
    code: Code2,
    corporate_fare: Building,
    create_new_folder: FolderPlus,
    data_object: Database,
    delete: Trash2,
    description: FileText,
    domain: Building2,
    download: Download,
    draft: FileText,
    edit: Edit3,
    engineering: Wrench,
    error: AlertCircle,
    expand_less: ChevronUp,
    expand_more: ChevronDown,
    folder: Folder,
    folder_off: CircleOff,
    folder_open: FolderOpen,
    folder_shared: UsersRound,
    folder_zip: FileArchive,
    group: UsersRound,
    group_off: UserX,
    hub: GitFork,
    image: Image,
    inbox: Inbox,
    info: Info,
    inventory_2: Box,
    list: List,
    lock: Lock,
    mail: Mail,
    movie: Video,
    open_in_new: ArrowRight,
    payments: Landmark,
    person: User,
    person_check: UserCheck,
    person_off: UserX,
    picture_as_pdf: FileText,
    radio_button_checked: Radio,
    refresh: RefreshCw,
    remove_circle: MinusCircle,
    schema: Waypoints,
    search: Search,
    security: Shield,
    share: Share2,
    slideshow: Presentation,
    sync: RefreshCw,
    table_chart: FileSpreadsheet,
    text_snippet: FileText,
    trending_up: TrendingUp,
    unfold_less: ChevronsUp,
    unfold_more: ChevronsDown,
    update: RefreshCw,
    upload: Upload,
    upload_file: FileUp,
    verified: BadgeCheck,
    verified_user: ShieldCheck,
    visibility: Eye,
}

export function AppIcon({ name, className, strokeWidth = 2, ...props }: AppIconProps) {
    const Icon = iconMap[String(name || '').trim()] || BadgeInfo

    return (
        <Icon
            aria-hidden="true"
            className={cn('app-icon inline-block shrink-0', className)}
            focusable="false"
            strokeWidth={strokeWidth}
            {...props}
        />
    )
}
