# Generated by Django 5.2.12 on 2026-04-01 15:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Role code (e.g., 'admin')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Role name (e.g., 'Administrator')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description', max_length=500)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted (Admin/Manager/User)')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], db_index=True, default='active', help_text='Account status: active, blocked, or inactive', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company name', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug', max_length=100, null=True, unique=True)),
                ('tax_code', models.CharField(blank=True, help_text='Tax identification number', max_length=50, null=True)),
                ('domain', models.CharField(blank=True, help_text='Company domain (e.g., company.com)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['is_deleted'], name='users_compa_is_dele_4c314f_idx'), models.Index(fields=['created_at'], name='users_compa_created_69584c_idx'), models.Index(fields=['updated_at'], name='users_compa_updated_fc9f73_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Department name', max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Department manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent department (for hierarchical structure)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='users.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.department'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('code', models.CharField(db_index=True, help_text="Permission code (e.g., 'document_read')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Permission name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Permission description', max_length=500)),
                ('resource', models.CharField(db_index=True, help_text="Resource (e.g., 'document', 'user', 'folder')", max_length=50)),
                ('action', models.CharField(help_text="Action (e.g., 'create', 'read', 'update', 'delete')", max_length=50)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='permissions_code_a0a529_idx'), models.Index(fields=['resource'], name='permissions_resourc_8c0693_idx'), models.Index(fields=['is_deleted'], name='permissions_is_dele_d0a893_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment')),
                ('account', models.ForeignKey(help_text='User account', on_delete=django.db.models.deletion.CASCADE, related_name='account_roles', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin who granted this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role', on_delete=django.db.models.deletion.CASCADE, related_name='account_role_mappings', to='users.role')),
            ],
            options={
                'verbose_name': 'Account Role',
                'verbose_name_plural': 'Account Roles',
                'db_table': 'account_roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(help_text='Permission', on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_mappings', to='users.permission')),
                ('role', models.ForeignKey(help_text='Role', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of user', max_length=100)),
                ('avatar_url', models.URLField(blank=True, help_text='Avatar URL (S3/CDN)', max_length=500, null=True)),
                ('address', models.TextField(blank=True, help_text="User's address", null=True)),
                ('birthday', models.DateField(blank=True, help_text="User's birthday", null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (phone, social_id, etc.)')),
                ('account', models.OneToOneField(help_text='Link to Account (authentication)', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text="User's department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'users',
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent_id'], name='departments_parent__acf920_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['manager_id'], name='departments_manager_b4328a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='departments_name_c59a45_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_deleted'], name='departments_is_dele_50501c_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='accounts_email_04e851_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='accounts_usernam_cab5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['status'], name='accounts_status_8b566b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['department'], name='accounts_departm_2ef663_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_deleted'], name='accounts_is_dele_3f7769_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['created_at'], name='accounts_created_1b6d37_idx'),
        ),
        migrations.AddIndex(
            model_name='accountrole',
            index=models.Index(fields=['account', 'role'], name='account_rol_account_8b4749_idx'),
        ),
        migrations.AddIndex(
            model_name='accountrole',
            index=models.Index(fields=['is_deleted'], name='account_rol_is_dele_581608_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountrole',
            unique_together={('account', 'role')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='role_permis_role_id_29a93b_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['is_deleted'], name='role_permis_is_dele_68cb6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['account_id'], name='users_account_f80812_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['department_id'], name='users_departm_5a2d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_deleted'], name='users_is_dele_21b557_idx'),
        ),
    ]
