# Generated by Django 5.2.12 on 2026-04-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_department'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_departm_2ef663_idx',
        ),
        migrations.AlterUniqueTogether(
            name='accountrole',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='accountrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('account', 'role'), name='unique_account_role_active'),
        ),
    ]
