# Generated by Django 5.2.12 on 2026-04-07 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_accounts_departm_2ef663_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Reset token (random string)', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Khi token được tạo')),
                ('expires_at', models.DateTimeField(help_text='Token hết hạn lúc (24 giờ sau)')),
                ('is_used', models.BooleanField(default=False, help_text='Đã được dùng chưa')),
                ('used_at', models.DateTimeField(blank=True, help_text='Khi token được dùng', null=True)),
                ('user', models.OneToOneField(help_text='User reset password', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'password_reset_tokens',
                'indexes': [models.Index(fields=['token'], name='password_re_token_060a1f_idx'), models.Index(fields=['user_id'], name='password_re_user_id_af59e2_idx'), models.Index(fields=['is_used'], name='password_re_is_used_eabc82_idx'), models.Index(fields=['expires_at'], name='password_re_expires_8e96b7_idx')],
            },
        ),
    ]
