# Generated by Django 5.2.12 on 2026-04-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE accounts DROP COLUMN IF EXISTS is_password_temporary;",
            reverse_sql="ALTER TABLE accounts ADD COLUMN is_password_temporary BOOLEAN DEFAULT true;",
            state_operations=[]
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
