# Generated by Django 5.2.12 on 2026-04-07 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Reset token (generated randomly)', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('is_used', models.BooleanField(default=False, help_text='Token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='Khi token được sử dụng', null=True)),
                ('is_admin_action', models.BooleanField(default=False, help_text='Token được tạo bởi Admin reset password')),
                ('account', models.ForeignKey(help_text='Account which can reset password', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, help_text='Admin who generated this token (if admin action)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='password_re_token_060a1f_idx'), models.Index(fields=['account_id'], name='password_re_account_dc7395_idx'), models.Index(fields=['expires_at'], name='password_re_expires_8e96b7_idx'), models.Index(fields=['is_used'], name='password_re_is_used_eabc82_idx')],
            },
        ),
    ]
