# Generated by Django 5.2.12 on 2026-05-07 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_account_id_alter_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Additional department managers (supports multiple managers)', related_name='managed_departments_m2m', to=settings.AUTH_USER_MODEL),
        ),
    ]
