# Generated by Django 5.2.12 on 2026-04-01 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPLOAD', 'Upload'), ('DELETE', 'Delete'), ('QUERY', 'Query'), ('EDIT', 'Edit'), ('DOWNLOAD', 'Download'), ('SHARE', 'Share'), ('DELETE_USER', 'Delete User'), ('CHANGE_ROLE', 'Change Role'), ('CREATE_ROLE', 'Create Role'), ('FEEDBACK', 'Feedback'), ('GRANT_ACL', 'Grant ACL'), ('REVOKE_ACL', 'Revoke ACL')], help_text='Action performed', max_length=100)),
                ('resource_id', models.UUIDField(blank=True, help_text='ID of affected resource (document/folder/user)', null=True)),
                ('query_text', models.TextField(blank=True, help_text='Query text (for QUERY action)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Source IP address', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device user agent', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Conversation title (auto-generated from first message)', max_length=255)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of conversation', null=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='ConversationAttachedDocument',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Conversation Attached Document',
                'verbose_name_plural': 'Conversation Attached Documents',
                'db_table': 'conversations_attached_documents',
            },
        ),
        migrations.CreateModel(
            name='ConversationAttachedFolder',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Conversation Attached Folder',
                'verbose_name_plural': 'Conversation Attached Folders',
                'db_table': 'conversations_attached_folders',
            },
        ),
        migrations.CreateModel(
            name='HumanFeedback',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], help_text='Rating (upvote or downvote)', max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Additional feedback comment', null=True)),
            ],
            options={
                'verbose_name': 'Human Feedback',
                'verbose_name_plural': 'Human Feedback',
                'db_table': 'human_feedback',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', help_text='Message role (user, assistant, system)', max_length=50)),
                ('content', models.TextField(help_text='Message content (1-10000 characters)')),
                ('citations', models.JSONField(blank=True, default=list, help_text='Array of citation objects with chunk info')),
                ('tokens_used', models.IntegerField(default=0, help_text='Token count for LLM cost calculation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='UserDocumentCache',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete')], default='read', help_text='Maximum permission level for this user on this document', max_length=50)),
                ('expires_at', models.DateTimeField(help_text='When this cache entry expires')),
            ],
            options={
                'verbose_name': 'User Document Cache',
                'verbose_name_plural': 'User Document Cache',
                'db_table': 'user_document_cache',
            },
        ),
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('EMBED_CHUNK', 'Embed Chunk'), ('SYNC_QDRANT', 'Sync Qdrant'), ('INDEX_DOCUMENT', 'Index Document'), ('CLEANUP', 'Cleanup'), ('REGENERATE_CACHE', 'Regenerate Cache')], help_text='Type of background task', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Task input data (content, model, parameters, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], default='pending', help_text='Task status', max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', help_text='Task priority for queue ordering', max_length=20)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts so far')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts')),
                ('scheduled_at', models.DateTimeField(auto_now_add=True, help_text='When task was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When worker started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When task completed successfully', null=True)),
                ('failed_reason', models.TextField(blank=True, help_text='Error message if task failed', null=True)),
                ('worker_id', models.CharField(blank=True, help_text='ID of worker processing this task', max_length=100, null=True)),
                ('backoff_multiplier', models.FloatField(default=2.0, help_text='Exponential backoff multiplier for retries')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='When to retry this task', null=True)),
                ('chunk', models.ForeignKey(blank=True, help_text='Associated chunk (if task is chunk-specific)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='async_tasks', to='documents.documentchunk')),
                ('document', models.ForeignKey(help_text='Associated document', on_delete=django.db.models.deletion.CASCADE, related_name='async_tasks', to='documents.document')),
            ],
            options={
                'verbose_name': 'Async Task',
                'verbose_name_plural': 'Async Tasks',
                'db_table': 'async_tasks',
            },
        ),
    ]
