# Generated by Django 5.2.12 on 2026-04-01 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='account',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='account',
            field=models.ForeignKey(help_text='User who owns this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationattacheddocument',
            name='conversation',
            field=models.ForeignKey(help_text='Conversation', on_delete=django.db.models.deletion.CASCADE, related_name='attached_documents', to='operations.conversation'),
        ),
        migrations.AddField(
            model_name='conversationattacheddocument',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Attached document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_attachments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='conversationattachedfolder',
            name='conversation',
            field=models.ForeignKey(help_text='Conversation', on_delete=django.db.models.deletion.CASCADE, related_name='attached_folders', to='operations.conversation'),
        ),
        migrations.AddField(
            model_name='conversationattachedfolder',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Attached folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_attachments', to='documents.folder'),
        ),
        migrations.AddField(
            model_name='humanfeedback',
            name='account',
            field=models.ForeignKey(help_text='User providing feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(help_text='Conversation containing this message', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operations.conversation'),
        ),
        migrations.AddField(
            model_name='humanfeedback',
            name='message',
            field=models.ForeignKey(help_text='Message being rated', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='operations.message'),
        ),
        migrations.AddField(
            model_name='userdocumentcache',
            name='account',
            field=models.ForeignKey(help_text='User (account)', on_delete=django.db.models.deletion.CASCADE, related_name='document_cache', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdocumentcache',
            name='document',
            field=models.ForeignKey(help_text='Cached document', on_delete=django.db.models.deletion.CASCADE, related_name='user_cache_entries', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='asynctask',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'retrying'])), fields=['status', 'priority'], name='idx_async_tasks_status_prio'),
        ),
        migrations.AddIndex(
            model_name='asynctask',
            index=models.Index(fields=['document_id', 'status'], name='async_tasks_documen_3a145d_idx'),
        ),
        migrations.AddIndex(
            model_name='asynctask',
            index=models.Index(fields=['scheduled_at', 'priority'], name='async_tasks_schedul_19870f_idx'),
        ),
        migrations.AddIndex(
            model_name='asynctask',
            index=models.Index(fields=['next_retry_at', 'status'], name='async_tasks_next_re_33dd06_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='idx_audit_logs_timestamp'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['account_id', 'created_at'], name='idx_audit_acct_time'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_id'], name='audit_logs_resourc_5afa9a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['account_id', 'updated_at'], name='idx_conversations_user_updated'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='idx_conversations_created_at'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_deleted'], name='conversatio_is_dele_864cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationattacheddocument',
            index=models.Index(fields=['conversation_id'], name='conversatio_convers_55236e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationattacheddocument',
            index=models.Index(fields=['document_id'], name='conversatio_documen_4dbef3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationattacheddocument',
            unique_together={('conversation', 'document')},
        ),
        migrations.AddIndex(
            model_name='conversationattachedfolder',
            index=models.Index(fields=['conversation_id'], name='conversatio_convers_5a4b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationattachedfolder',
            index=models.Index(fields=['folder_id'], name='conversatio_folder__d5b871_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationattachedfolder',
            unique_together={('conversation', 'folder')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation_id', 'created_at'], name='idx_messages_conv_timestamp'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation_id'], name='idx_messages_conversation'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted'], name='messages_is_dele_54348c_idx'),
        ),
        migrations.AddIndex(
            model_name='humanfeedback',
            index=models.Index(fields=['message_id'], name='human_feedb_message_aa0e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='humanfeedback',
            index=models.Index(fields=['account_id'], name='human_feedb_account_081fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='humanfeedback',
            index=models.Index(fields=['rating'], name='human_feedb_rating_2e95ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='humanfeedback',
            unique_together={('message', 'account')},
        ),
        migrations.AddIndex(
            model_name='userdocumentcache',
            index=models.Index(fields=['account_id', 'document_id', 'is_deleted'], name='user_docume_account_dc2171_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocumentcache',
            index=models.Index(fields=['account_id', 'updated_at'], name='idx_cache_user_updated'),
        ),
        migrations.AddIndex(
            model_name='userdocumentcache',
            index=models.Index(fields=['expires_at'], name='user_docume_expires_26e5e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdocumentcache',
            unique_together={('account', 'document')},
        ),
    ]
