# Generated by Django 5.2.13 on 2026-04-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        ('operations', '0003_alter_auditlog_resource_id'),
    ]

    operations = [
    ]
