# Generated by Django 5.2.13 on 2026-04-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_merge_0002_initial_0003_alter_auditlog_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPLOAD', 'Upload'), ('DELETE', 'Delete'), ('QUERY', 'Query'), ('EDIT', 'Edit'), ('UPDATE', 'Update'), ('DOWNLOAD', 'Download'), ('SHARE', 'Share'), ('IMPORT', 'Import'), ('DELETE_USER', 'Delete User'), ('CHANGE_ROLE', 'Change Role'), ('CREATE_ROLE', 'Create Role'), ('FEEDBACK', 'Feedback'), ('GRANT_ACL', 'Grant ACL'), ('REVOKE_ACL', 'Revoke ACL'), ('MUTATION', 'Mutation')], help_text='Action performed', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.UUIDField(blank=True, help_text='ID of affected resource (document/folder/user)', null=True),
        ),
    ]
