# Generated by Django 5.2.12 on 2026-05-07 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_auditlog_action_alter_auditlog_resource_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conversatio_is_dele_864cfb_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_account_3c85a0_idx',
            old_name='idx_conversations_user_updated',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_created_694913_idx',
            old_name='idx_conversations_created_at',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='account',
            field=models.ForeignKey(help_text='Owner of the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary of conversation', null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(help_text='Conversation title', max_length=255),
        ),
        migrations.AlterField(
            model_name='humanfeedback',
            name='rating',
            field=models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], help_text='Rating from 1 to 5 stars', max_length=50),
        ),
    ]
