from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_remove_conversation_conversatio_is_dele_864cfb_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("CREATE", "Create"),
                    ("UPLOAD", "Upload"),
                    ("DELETE", "Delete"),
                    ("QUERY", "Query"),
                    ("EDIT", "Edit"),
                    ("UPDATE", "Update"),
                    ("DOWNLOAD", "Download"),
                    ("SHARE", "Share"),
                    ("IMPORT", "Import"),
                    ("MOVE", "Move"),
                    ("DELETE_USER", "Delete User"),
                    ("CREATE_USER", "Create User"),
                    ("UPDATE_ACCOUNT", "Update Account"),
                    ("DEACTIVATE_ACCOUNT", "Deactivate Account"),
                    ("CHANGE_PASSWORD", "Change Password"),
                    ("FORGOT_PASSWORD", "Forgot Password"),
                    ("RESET_PASSWORD", "Reset Password"),
                    ("ADMIN_RESET_PASSWORD", "Admin Reset Password"),
                    ("UPDATE_OWN_PROFILE", "Update Own Profile"),
                    ("UPLOAD_AVATAR", "Upload Avatar"),
                    ("UPDATE_USER_PROFILE", "Update User Profile"),
                    ("CHANGE_USER_STATUS", "Change User Status"),
                    ("CHANGE_ROLE", "Change Role"),
                    ("ASSIGN_ROLE", "Assign Role"),
                    ("REMOVE_ROLE", "Remove Role"),
                    ("REPLACE_ROLE", "Replace Role"),
                    ("CHANGE_ACCOUNT_DEPARTMENT", "Change Account Department"),
                    ("CREATE_ROLE", "Create Role"),
                    ("UPDATE_ROLE", "Update Role"),
                    ("DELETE_ROLE", "Delete Role"),
                    ("GRANT_ROLE", "Grant Role"),
                    ("REVOKE_ROLE", "Revoke Role"),
                    ("ASSIGN_PERMISSION", "Assign Permission"),
                    ("REMOVE_PERMISSION", "Remove Permission"),
                    ("UPDATE_PERMISSION", "Update Permission"),
                    ("DELETE_PERMISSION", "Delete Permission"),
                    ("CREATE_DOCUMENT", "Create Document"),
                    ("DOCUMENT_UPLOAD", "Document Upload"),
                    ("DOCUMENT_DOWNLOAD", "Document Download"),
                    ("CREATE_FOLDER", "Create Folder"),
                    ("UPDATE_FOLDER", "Update Folder"),
                    ("DELETE_FOLDER", "Delete Folder"),
                    ("MOVE_FOLDER", "Move Folder"),
                    ("GRANT_PERMISSION", "Grant Permission"),
                    ("REVOKE_PERMISSION", "Revoke Permission"),
                    ("FEEDBACK", "Feedback"),
                    ("GRANT_ACL", "Grant ACL"),
                    ("REVOKE_ACL", "Revoke ACL"),
                    ("MUTATION", "Mutation"),
                ],
                help_text="Action performed",
                max_length=100,
            ),
        ),
    ]
