from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_expand_auditlog_action_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Type of affected resource (document/folder/user/chat/etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("denied", "Denied"),
                    ("pending", "Pending"),
                ],
                db_index=True,
                default="success",
                help_text="Outcome of the action",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="http_method",
            field=models.CharField(
                blank=True,
                help_text="HTTP method that triggered the action",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="API path that triggered the action",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status_code",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="HTTP response status code",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional non-sensitive audit metadata",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("READ", "Read"),
                    ("CREATE", "Create"),
                    ("UPLOAD", "Upload"),
                    ("DELETE", "Delete"),
                    ("QUERY", "Query"),
                    ("EDIT", "Edit"),
                    ("UPDATE", "Update"),
                    ("DOWNLOAD", "Download"),
                    ("SHARE", "Share"),
                    ("IMPORT", "Import"),
                    ("MOVE", "Move"),
                    ("DELETE_USER", "Delete User"),
                    ("CREATE_USER", "Create User"),
                    ("UPDATE_ACCOUNT", "Update Account"),
                    ("DEACTIVATE_ACCOUNT", "Deactivate Account"),
                    ("CHANGE_PASSWORD", "Change Password"),
                    ("FORGOT_PASSWORD", "Forgot Password"),
                    ("RESET_PASSWORD", "Reset Password"),
                    ("ADMIN_RESET_PASSWORD", "Admin Reset Password"),
                    ("UPDATE_OWN_PROFILE", "Update Own Profile"),
                    ("UPLOAD_AVATAR", "Upload Avatar"),
                    ("UPDATE_USER_PROFILE", "Update User Profile"),
                    ("CHANGE_USER_STATUS", "Change User Status"),
                    ("CHANGE_ROLE", "Change Role"),
                    ("ASSIGN_ROLE", "Assign Role"),
                    ("REMOVE_ROLE", "Remove Role"),
                    ("REPLACE_ROLE", "Replace Role"),
                    ("CHANGE_ACCOUNT_DEPARTMENT", "Change Account Department"),
                    ("CREATE_ROLE", "Create Role"),
                    ("UPDATE_ROLE", "Update Role"),
                    ("DELETE_ROLE", "Delete Role"),
                    ("GRANT_ROLE", "Grant Role"),
                    ("REVOKE_ROLE", "Revoke Role"),
                    ("ASSIGN_PERMISSION", "Assign Permission"),
                    ("REMOVE_PERMISSION", "Remove Permission"),
                    ("UPDATE_PERMISSION", "Update Permission"),
                    ("DELETE_PERMISSION", "Delete Permission"),
                    ("RESTORE", "Restore"),
                    ("CREATE_DOCUMENT", "Create Document"),
                    ("DOCUMENT_UPLOAD", "Document Upload"),
                    ("DOCUMENT_DOWNLOAD", "Document Download"),
                    ("CREATE_FOLDER", "Create Folder"),
                    ("UPDATE_FOLDER", "Update Folder"),
                    ("DELETE_FOLDER", "Delete Folder"),
                    ("MOVE_FOLDER", "Move Folder"),
                    ("GRANT_PERMISSION", "Grant Permission"),
                    ("REVOKE_PERMISSION", "Revoke Permission"),
                    ("FEEDBACK", "Feedback"),
                    ("GRANT_ACL", "Grant ACL"),
                    ("REVOKE_ACL", "Revoke ACL"),
                    ("CHAT_MESSAGE", "Chat Message"),
                    ("ACCESS_DENIED", "Access Denied"),
                    ("ERROR", "Error"),
                    ("MUTATION", "Mutation"),
                ],
                help_text="Action performed",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["status", "created_at"], name="audit_logs_status_356ed1_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["resource_type", "created_at"], name="audit_logs_resourc_d25499_idx"),
        ),
    ]
