from typing import List, Dict, Any, Optional
import logging
from django.apps import apps
from django.core.cache import cache
from django.conf import settings

logger = logging.getLogger(__name__)


class HybridRetriever:
    """Hybrid retriever combining sparse (BM25 full-text) and dense (vector) search.

    Design:
    - Sparse search: BM25 via PostgreSQL full-text search (much better than icontains)
    - Dense search: Vector similarity via Qdrant
    - Query embedding: Generated by injected embedding_client
    - Results merged with: sparse (40%) + dense (60%) weighted scores

    BM25 provides:
    - Term frequency saturation (not dominated by term count)
    - Inverse document frequency (rare terms weighted higher)
    - Field length normalization (longer docs not unfairly boosted)
    - Better ranking than naive substring matching
    """

    def __init__(self, qdrant_client, embedding_client, sparse_boost: float = 1.0):
        self.qdrant = qdrant_client
        self.embedding_client = embedding_client
        self.sparse_boost = sparse_boost  # BM25 already returns normalized scores
        self.cache_ttl = getattr(settings, 'CACHE_TTL', 600)
        
        # Initialize BM25 searcher
        try:
            from .bm25_searcher import BM25Searcher
            self.bm25 = BM25Searcher()
            logger.info("BM25 sparse search initialized")
        except Exception as e:
            logger.warning(f"BM25 initialization failed, will fall back to icontains: {e}")
            self.bm25 = None

    def retrieve(self, query: str, top_k: int = 10, sparse_k: int = 10) -> List[Dict[str, Any]]:
        """Return merged list of candidate chunks with scores.

        Each item: {chunk_id, document_id, score, source, snippet}
        
        Scoring Strategy:
        1. Sparse search (BM25): Term frequency + IDF + field length normalization
        2. Dense search: Vector similarity [0, 1]
        3. Merge: Normalize both to [0, 1], combine with weights
           - Sparse: 40% (lexical relevance)
           - Dense: 60% (semantic relevance)
        
        BM25 advantages over icontains:
        - Doesn't just count term occurrences
        - Weights rare terms higher (IDF)
        - Avoids length bias
        - More relevant results for keyword queries
        """
        cache_key = f"hybrid_retrieval:{query}:{top_k}:{sparse_k}"
        try:
            cached = cache.get(cache_key)
            if cached:
                logger.debug("Hybrid retrieval cache hit")
                return cached
        except Exception:
            pass

        candidates: Dict[str, Dict[str, Any]] = {}
        sparse_scores: Dict[str, float] = {}
        dense_scores: Dict[str, float] = {}

        # 1) Sparse search: BM25 (or fallback to icontains if BM25 unavailable)
        max_sparse = 0.0
        try:
            if self.bm25:
                # Use BM25 full-text search
                sparse_results = self.bm25.search(query, top_k=sparse_k)
                for result in sparse_results:
                    cid = result['chunk_id']
                    score = float(result['score']) * self.sparse_boost
                    candidates[cid] = {
                        'chunk_id': cid,
                        'document_id': result['document_id'],
                        'score': 0.0,  # Will be set after normalization
                        'source': 'bm25',
                        'snippet': result['content'][:300]
                    }
                    sparse_scores[cid] = score
                    max_sparse = max(max_sparse, score)
                logger.debug(f"BM25 sparse search returned {len(sparse_results)} results")
            else:
                # Fallback: simple icontains (less effective but reliable)
                logger.debug("Using icontains fallback for sparse search")
                from repositories.document_repository import DocumentRepository
                doc_repo = DocumentRepository()
                
                sparse_docs = doc_repo.search(query)[:5]  # Reduced from sparse_k
                for doc in sparse_docs:
                    chunks_qs = apps.get_model('documents', 'DocumentChunk').objects.filter(
                        document_id=doc.id, is_deleted=False
                    ).filter(content__icontains=query).order_by('chunk_index')[:3]
                    
                    for c in chunks_qs:
                        cid = str(c.id)
                        score = 1.0 * self.sparse_boost  # Uniform score for icontains
                        candidates[cid] = {
                            'chunk_id': cid,
                            'document_id': str(c.document_id),
                            'score': 0.0,
                            'source': 'icontains_fallback',
                            'snippet': (c.content or '')[:300]
                        }
                        sparse_scores[cid] = score
                        max_sparse = max(max_sparse, score)
        
        except Exception as e:
            logger.warning(f"Sparse retrieval error: {e}", exc_info=True)

        # 2) Dense search: Vector similarity
        max_dense = 0.0
        try:
            embedding = self.embedding_client.create_embedding(query)
            dense_results = self.qdrant.search_similar(embedding=embedding, limit=top_k)
            
            for vector_id, score, payload in dense_results:
                cid = str(payload.get('chunk_id') or vector_id)
                score = float(score or 0.0)
                payload = payload or {}
                
                dense_scores[cid] = score
                max_dense = max(max_dense, score)
                
                if cid in candidates:
                    # Already found in sparse, mark as hybrid
                    candidates[cid]['source'] = 'hybrid'
                else:
                    candidates[cid] = {
                        'chunk_id': cid,
                        'document_id': str(payload.get('document_id') or payload.get('doc_id') or ''),
                        'score': 0.0,
                        'source': 'dense',
                        'snippet': (payload.get('text_preview') or '')[:300]
                    }
        
        except Exception as e:
            logger.warning(f"Dense retrieval error: {e}", exc_info=True)

        # 3) Normalize and combine scores
        # Important: normalize to [0, 1] before combining
        if max_sparse > 0:
            for cid in sparse_scores:
                sparse_scores[cid] = sparse_scores[cid] / max_sparse
        if max_dense > 0:
            for cid in dense_scores:
                dense_scores[cid] = dense_scores[cid] / max_dense

        # Combine with weights: 40% sparse (keyword) + 60% dense (semantic)
        for cid, candidate in candidates.items():
            sparse_norm = sparse_scores.get(cid, 0.0)
            dense_norm = dense_scores.get(cid, 0.0)
            combined_score = 0.4 * sparse_norm + 0.6 * dense_norm
            candidate['score'] = combined_score

        # 4) Sort by combined score
        sorted_candidates = sorted(candidates.values(), key=lambda x: x['score'], reverse=True)
        
        # Log retrieval quality
        hybrid_count = sum(1 for c in sorted_candidates if c['source'] == 'hybrid')
        sparse_count = sum(1 for c in sorted_candidates if c['source'] in ['bm25', 'icontains_fallback'])
        dense_count = sum(1 for c in sorted_candidates if c['source'] == 'dense')
        
        logger.debug(
            f"Hybrid retrieval: {len(sorted_candidates)} results "
            f"({hybrid_count} hybrid, {sparse_count} sparse, {dense_count} dense)"
        )
        
        result = sorted_candidates[:top_k]
        try:
            cache.set(cache_key, result, self.cache_ttl)
        except Exception as e:
            logger.debug(f"Hybrid retrieval cache set failed: {e}")
        return result
