# Generated by Django 5.2.12 on 2026-04-01 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Stored filename', max_length=255)),
                ('original_name', models.CharField(help_text='Original filename from upload', max_length=255)),
                ('storage_path', models.TextField(help_text='Full path in storage (S3, local, etc.)')),
                ('file_type', models.CharField(help_text='File type (pdf, docx, txt, markdown)', max_length=50)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type', max_length=100, null=True)),
                ('access_scope', models.CharField(choices=[('personal', 'Personal'), ('department', 'Department'), ('company', 'Company')], default='company', help_text='Access scope (personal, department, company)', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='Is publicly accessible?')),
                ('doc_language', models.CharField(default='vi', help_text='Document language (vi, en, etc.)', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('version', models.IntegerField(default=1, help_text='Version number (for updates)')),
                ('embedding_model', models.CharField(default='mistral-embed', help_text='Embedding model used', max_length=100)),
                ('chunking_strategy', models.CharField(default='recursive_character_1000_200', help_text='Chunking strategy (e.g., recursive_character_1000_200)', max_length=100)),
                ('s3_url', models.URLField(blank=True, help_text='S3 URL for direct access', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Processing status', max_length=50)),
                ('version_lock', models.IntegerField(default=1, help_text='Version lock for optimistic concurrency control')),
                ('has_hierarchical_chunks', models.BooleanField(default=False, help_text='Does this document have hierarchical chunks (parent-child)?')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('summary', 'Summary'), ('detail', 'Detail'), ('section', 'Section')], default='detail', help_text='Chunk type (summary, detail, section)', max_length=50)),
                ('vector_id', models.CharField(blank=True, help_text='ID in Qdrant vector database', max_length=255, null=True)),
                ('content', models.TextField(help_text='Chunk content text')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary', null=True)),
                ('page_number', models.IntegerField(default=1, help_text='Page number in source document')),
                ('chunk_index', models.IntegerField(default=0, help_text='Sequential index of chunk')),
                ('token_count', models.IntegerField(default=0, help_text='Token count (for cost calculation)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (position, heading, etc.)')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'db_table': 'document_chunks',
            },
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_model', models.CharField(default='Q wen3-4B-Instruct-2507-Q4_K_M', help_text='Model used for embedding', max_length=100)),
                ('embedding_dimension', models.IntegerField(default=1536, help_text='Vector dimension')),
                ('embedding_vector', models.TextField(blank=True, help_text='Vector as JSON (optional - usually in Qdrant)', null=True)),
                ('qdrant_vector_id', models.CharField(blank=True, help_text='Vector ID in Qdrant database', max_length=255, null=True, unique=True)),
                ('qdrant_score', models.FloatField(blank=True, help_text='Similarity score from last Qdrant search', null=True)),
                ('embedding_computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Embedding',
                'verbose_name_plural': 'Document Embeddings',
                'db_table': 'document_embeddings',
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('role', 'Role'), ('account', 'Account')], help_text='Type of subject (role or account)', max_length=50)),
                ('subject_id', models.CharField(help_text='ID of role (UUID) or account (BIGINT)', max_length=255)),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete')], default='read', help_text='Permission level (read, write, delete)', max_length=50)),
                ('permission_precedence', models.CharField(choices=[('inherit', 'Inherit'), ('override', 'Override'), ('deny', 'Deny')], default='inherit', help_text='Permission precedence (inherit from folder, override, or deny)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this permission active?')),
            ],
            options={
                'verbose_name': 'Document Permission',
                'verbose_name_plural': 'Document Permissions',
                'db_table': 'document_permissions',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Folder name', max_length=100)),
                ('access_scope', models.CharField(choices=[('personal', 'Personal'), ('department', 'Department'), ('company', 'Company')], default='company', help_text='Access scope (personal, department, company)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Folder description', max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'db_table': 'folders',
            },
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('role', 'Role'), ('account', 'Account')], help_text='Type of subject (role or account)', max_length=50)),
                ('subject_id', models.CharField(help_text='ID of role (UUID) or account (BIGINT)', max_length=255)),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete')], default='read', help_text='Permission level (read, write, delete)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this permission active?')),
            ],
            options={
                'verbose_name': 'Folder Permission',
                'verbose_name_plural': 'Folder Permissions',
                'db_table': 'folder_permissions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tag name', max_length=100)),
                ('color', models.CharField(default='#000000', help_text='Hex color code', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Tag description', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
    ]
