# Generated by Django 5.2.12 on 2026-04-01 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Associated department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='users.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(help_text='Parent document', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='next_chunk',
            field=models.ForeignKey(blank=True, help_text='Next chunk in sequence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_chunk_ref', to='documents.documentchunk'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='parent_node',
            field=models.ForeignKey(blank=True, help_text='Parent chunk (hierarchical structure)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='documents.documentchunk'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='prev_chunk',
            field=models.ForeignKey(blank=True, help_text='Previous chunk in sequence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_chunk_ref', to='documents.documentchunk'),
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='chunk',
            field=models.ForeignKey(help_text='Chunk being embedded', on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='documents.documentchunk'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='document',
            field=models.ForeignKey(help_text='Document being permission-controlled', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='folder',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Associated department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='users.department'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent folder (hierarchical structure)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='documents.folder'),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder containing this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.folder'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='folder',
            field=models.ForeignKey(help_text='Folder being permission-controlled', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.folder'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this tag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Associated tags', related_name='documents', to='documents.tag'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document_id'], name='document_ch_documen_53de58_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['parent_node_id'], name='document_ch_parent__5c55be_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['vector_id'], name='document_ch_vector__133003_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['page_number'], name='document_ch_page_nu_91bcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['prev_chunk_id'], name='idx_chunk_prev'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['next_chunk_id'], name='idx_chunk_next'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['is_deleted'], name='document_ch_is_dele_d21048_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['chunk_id'], name='document_em_chunk_i_1bccff_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['qdrant_vector_id'], name='document_em_qdrant__2c9d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['embedding_model'], name='document_em_embeddi_8c3d56_idx'),
        ),
        migrations.AddIndex(
            model_name='documentembedding',
            index=models.Index(fields=['created_at'], name='document_em_created_702258_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentembedding',
            unique_together={('chunk', 'embedding_model')},
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['document_id'], name='document_pe_documen_6c92bd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['subject_type', 'subject_id'], name='document_pe_subject_cde363_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['permission_precedence'], name='document_pe_permiss_0f1663_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['is_deleted'], name='document_pe_is_dele_5c660c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('document', 'subject_type', 'subject_id')},
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent_id'], name='folders_parent__95398b_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['department_id'], name='folders_departm_b2813e_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['name'], name='folders_name_f46f54_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['is_deleted'], name='folders_is_dele_08a3ee_idx'),
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['folder_id'], name='folder_perm_folder__36717c_idx'),
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['subject_type', 'subject_id'], name='folder_perm_subject_bb67f8_idx'),
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['is_deleted'], name='folder_perm_is_dele_8f6f1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderpermission',
            unique_together={('folder', 'subject_type', 'subject_id')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploader_id'], name='documents_uploade_585fed_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['department_id', 'is_deleted'], name='documents_departm_f5f636_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['folder_id', 'is_deleted'], name='documents_folder__98a0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'is_deleted'], name='documents_status_2cd3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='idx_documents_created_at'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_deleted'], name='documents_is_dele_636b14_idx'),
        ),
    ]
