# Generated by Django 5.2.12 on 2026-04-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('users', '0012_alter_account_id_alter_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to='users.account'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['created_by_id'], name='folders_created_a20dd9_idx'),
        ),
    ]
