# Generated by Django 5.2.13 on 2026-04-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_folder_created_by_folder_folders_created_a20dd9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(help_text='File type (pdf, docx, txt, markdown)', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, help_text='MIME type', max_length=255, null=True),
        ),
    ]
