# Generated by Django 5.2.13 on 2026-05-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file_type_alter_document_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpermission',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='read', help_text='Permission level (read, write, admin)', max_length=50),
        ),
        migrations.AlterField(
            model_name='folderpermission',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], default='read', help_text='Permission level (read, write, admin)', max_length=50),
        ),
    ]
