# Generated by Django 5.2.12 on 2026-05-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_fix_permission_levels'),
        ('documents', '0006_fix_permission_levels'),
    ]

    operations = [
    ]
