# Generated by Django 5.2.14 on 2026-05-16 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_add_fts_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - True = deleted, False = active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp (null = not deleted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp (auto-filled)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp (auto-updated)')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('pdf_embedded', 'PDF Embedded Image'), ('pdf_page_render', 'PDF Page Render'), ('docx_inline', 'DOCX Inline Image'), ('docx_header', 'DOCX Header Image'), ('xlsx_image', 'XLSX Embedded Image'), ('xls_image', 'XLS Embedded Image'), ('other', 'Other')], help_text='Loại asset (nguồn gốc)', max_length=50)),
                ('page_number', models.IntegerField(blank=True, help_text='Số trang (PDF) hoặc sheet index (Excel)', null=True)),
                ('sheet_name', models.CharField(blank=True, help_text='Tên sheet (Excel)', max_length=255, null=True)),
                ('anchor_cell', models.CharField(blank=True, help_text='Ô anchor Excel: G9, F8', max_length=20, null=True)),
                ('anchor_row', models.IntegerField(blank=True, help_text='Số dòng anchor trong Excel', null=True)),
                ('paragraph_index', models.IntegerField(blank=True, help_text='Thứ tự paragraph trong DOCX', null=True)),
                ('position_in_document', models.JSONField(blank=True, default=dict, help_text='{x, y, width, height} trên trang')),
                ('image_path', models.TextField(help_text='Đường dẫn: media/document_assets/{doc_id}/...')),
                ('image_format', models.CharField(default='png', help_text='png, jpg, webp', max_length=10)),
                ('image_width', models.IntegerField(blank=True, help_text='Chiều rộng pixels', null=True)),
                ('image_height', models.IntegerField(blank=True, help_text='Chiều cao pixels', null=True)),
                ('image_size_bytes', models.IntegerField(default=0, help_text='Kích thước file bytes')),
                ('ocr_text', models.TextField(blank=True, help_text='Kết quả OCR từ Tesseract', null=True)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='Độ tin cậy OCR trung bình (0-100)', null=True)),
                ('ocr_language', models.CharField(default='vie', help_text='vie, eng, vie+eng', max_length=20)),
                ('caption', models.TextField(blank=True, help_text='Caption từ Qwen2.5-VL: mô tả nội dung ảnh', null=True)),
                ('caption_model', models.CharField(default='qwen25-vl-3b', help_text='Model tạo caption', max_length=100)),
                ('caption_raw_response', models.TextField(blank=True, help_text='Response gốc từ VL model', null=True)),
                ('context_text', models.TextField(blank=True, help_text='Text xung quanh ảnh (paragraph/sheet/row)', null=True)),
                ('context_range', models.JSONField(blank=True, default=dict, help_text='{start_char, end_char}')),
                ('caption_embedding_id', models.CharField(blank=True, help_text='Vector ID trong Qdrant (collection: document_assets)', max_length=255, null=True)),
                ('embedding_model', models.CharField(default='bge-m3', help_text='Model embed caption', max_length=100)),
                ('embedding_dimension', models.IntegerField(default=1024, help_text='Số chiều vector embedding')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('ocr_done', 'OCR Done'), ('captioned', 'Captioned'), ('embedded', 'Embedded'), ('failed', 'Failed')], default='pending', help_text='Trạng thái xử lý asset', max_length=50)),
                ('processing_error', models.TextField(blank=True, help_text='Lỗi nếu failed', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Thời điểm xử lý xong', null=True)),
            ],
            options={
                'verbose_name': 'Document Asset',
                'verbose_name_plural': 'Document Assets',
                'db_table': 'document_assets',
                'ordering': ['page_number', 'paragraph_index'],
            },
        ),
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='docchunk_search_vec_gin',
            old_name='documentchunk_search_vector_gin_idx',
        ),
        migrations.AddField(
            model_name='documentasset',
            name='chunk',
            field=models.ForeignKey(blank=True, help_text='DocumentChunk gần nhất chứa asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='documents.documentchunk'),
        ),
        migrations.AddField(
            model_name='documentasset',
            name='document',
            field=models.ForeignKey(help_text='Tài liệu cha chứa asset này', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['document_id'], name='document_as_documen_e70859_idx'),
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['chunk_id'], name='document_as_chunk_i_fd54e9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['asset_type'], name='document_as_asset_t_445310_idx'),
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['processing_status'], name='document_as_process_8fc655_idx'),
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['page_number'], name='document_as_page_nu_4b6aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['sheet_name', 'anchor_cell'], name='document_as_sheet_n_3b6d71_idx'),
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['caption_embedding_id'], name='document_as_caption_cd4916_idx'),
        ),
        migrations.AddIndex(
            model_name='documentasset',
            index=models.Index(fields=['is_deleted'], name='document_as_is_dele_34d2c8_idx'),
        ),
    ]
